#!perl
use strict;
use warnings;
use Judy::HS qw( JHSI JHSG );

my $judy = 0;
while ( <> ) {
    my ( $ptr, $val ) = JHSG( $judy, $_ );
    print if ! $ptr;
    ( undef, $judy ) = JHSI( $judy, $_, 0 );
}
