
=head1 NAME

Judy::HS - Library for creating and accessing a dynamic array, using an array-of-bytes as an Key and a word as a Value. 



=head1 SYNOPSIS

Shows an ultra-cheap hash for removing duplicates.

  my $judy = 0;
  while (<>) {
    my ($ptr,$val) = Get( $judy, $_ );
    print if ! $ptr;
    Set( $judy, $_, 1 );
  }

=head1 DESCRIPTION

Judy::HS is an interface to the JudyHS macros in the Judy array library.

A JudyHS array is the equivalent of an array of word-sized
value/pointers. An Key is a pointer to an array-of-bytes. Rather than
using a null terminated string, this difference from JudySL(3X) allows
strings to contain all bits (specifically the null character). This
new addition (May 2004) to Judy arrays is a hybrid using the best
capabilities of hashing and Judy methods. JudyHS does not have a poor
performance case where knowledge of the hash algorithm can be used to
degrade the performance.

Since JudyHS is based on a hash method, Keys are not stored in any
particular order. Therefore the JudyHSFirst(), JudyHSNext(),
JudyHSPrev() and JudyHSLast() neighbor search functions are not
practical.

The hallmark of JudyHS is speed with scalability, but memory
efficiency is excellent. The speed is very competitive with the best
hashing methods. The memory efficiency is similar to a linked list of
the same Keys and Values. JudyHS is designed to scale from 0 to
billions of Keys.

A JudyHS array is allocated with an undefined or 0 value.

    my $judy = 0;



=head1 EXPORT

All functions are exportable by L<Sub::Exporter>.



=head1 DATA TYPES

=over

=item *

$PValue - JudyHS array element. A pointer cast to integer.

=item *

$Rc_int - return flag.

=item *

$Rc_word - full word return value

=item *

$Judy - JudyHS array

=item *

$Key - array-of-bytes pointer

=back



=head1 BASIC FUNCTIONS

=head2 $PValue = Set( $Judy, $Key, $Value )

Given a pointer to a JudyHS array (C<$Judy>), insert an C<$Key>
string and a C<$Value> into the JudyHS array:
C<$Judy>. Sets the value to $Value.

Note: Set() and Delete can reorganize the JudyHS array. Therefore,
pointers returned from previous JudyHS calls become invalid and must
be re-acquired (using Get()).

=head2 $Rc_int = Delete( $Judy, $Key )

Given a pointer to a JudyHS array (C<$Judy>), delete the
specified C<$Key> along with the C<$Value> from the JudyHS array.

Return C<$Rc_int> set to 1 if successfully removed from the
array. Return C<$Rc_int> set to 0 if C<$Key> was not present.

=head2 ( $PValue, $Value ) = Get( $Judy, $Key )

Given a pointer to a JudyHS array (C<$Judy>), find C<$Value>
associated with C<$Key>.

If C<$Key> is in the hash, return C<$PValue> a pointer to C<$Value>
and C<$Value>. Return nothing if C<$Key> is not in the hash.

=head2 $Rc_word = Free( $Judy )

Given a pointer to a JudyHS array (C<$Judy>), free the entire array.

Return C<$Rc_word> set to the number of bytes freed and C<$Judy>
set to NULL.



=head1 AUTHOR

Joshua ben Jore, C<< <jjore at cpan.org> >>

JudyHS was invented and implemented by Doug Baskins after retiring from Hewlett-Packard.



=head1 SOURCE AVAILABILITY

This source is in Github: L<git://github.com/jbenjore/judy-hs.git>



=head1 BUGS

Please report any bugs or feature requests to C<bug-Judy-HS at
rt.cpan.org>, or through the web interface at
L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Judy-HS>.  I will be
notified, and then you'll automatically be notified of progress on
your bug as I make changes.



=head1 SUPPORT

You can find documentation for this module with the perldoc command.

  perldoc Judy::HS

You can also look for information at:

=over

=item * RT: CPAN's request tracker

L<http://rt.cpan.org/NoAuth/Bugs.html?Dist=Judy::HS>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/Judy::HS>

=item * CPAN Ratings

L<http://cpanratings.perl.org/d/Judy::HS>

=item * Search CPAN

L<http://search.cpan.org/dist/Judy::HS/>

=back



=head1 ACKNOWLEDGEMENTS

Doug Baskins, totally.



=head1 COPYRIGHT & LICENSE

Copyright 2008 Joshua ben Jore, all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
